import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainNavbar } from "./components/main-navbar";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "./components/footer";


const panchang = localFont({
    src: "../../public/fonts/Panchang-Regular.woff2",
    variable: "--font-panchang",
});

const supreme = localFont({
  src: "../../public/fonts/Supreme-Regular.woff2",
  variable: "--font-supreme",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${panchang.variable} ${supreme.variable} font-sans antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MainNavbar />
          <div className="flex-1 flex flex-col">
            {children}
          </div>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
